# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :main do

    # Checkout release branch
    #ensure_git_status_clean

    # Clear cache
    clear_derived_data
    xcclean(
        scheme: "GeekShop",
        workspace: "GeekShop.xcworkspace"
    )

    # Update Pods
    cocoapods(
        use_bundle_exec: false
    )

    # Tests
    run_tests

  end
end
